# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: cd1caa72b02b64185d9394fff1d0d122996f5ad0 $
Configuration parameters:
  url = https://wiki.wikimedia.cz/mw/
  name = inner_wiki

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'inner_wiki'
        self.langs = {
            'cs': 'wiki.wikimedia.cz',
        }

    def scriptpath(self, code):
        return {
            'cs': '/mw',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'cs': u'1.31.0-wmf.10',
        }[code]

    def protocol(self, code):
        return {
            'cs': u'https',
        }[code]
